version: '3'
services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    restart: always
    ports:
      - '5432:5432'
    networks:
      - kafka-net
    environment:
      POSTGRES_PASSWORD: C7SQKr@g6SwtXNi
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    volumes:
      - ./setup.sh:/setup.sh
      - ./messages:/messages
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "k8s-resources:1:1"
    networks:
      - kafka-net
networks:
  kafka-net:
    driver: bridge
